remote_theme: qwtel/hydejack
title: Abraham Cruz
plugins:
  - jekyll-paginate
# Pagination configuration (used by the `blog` layout)
paginate:              5
paginate_path:         /blog/page-:num/

# Menu in the sidebar
menu:
  - title:             About
    url:               /about

# Footer
copyright:             © 2019. All rights reserved.

# Format of the permalinks
permalink:             /:categories/:year-:month-:day-:title/

# Theme configurations
hydejack:
  dark_mode:
    always:            true

# Blog configuration
# defaults:
#   - scope:
#       type: posts
#     values:
#       permalink: /posts/:title/

# File inclusion/exclusion
# ========================================================================================

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - "*.gemspec"
  - _js
  - _plugins
  - .sass-cache

# Plugins
# ========================================================================================

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings


