baseURL = 'https://abrahamsustaita.com/'
languageCode = 'en-us'
title = 'abe@blinkin $'

theme = 'terminal'

[Params]
  contentTypeName = "posts"
  enableGitInfo = true
  fullWidthTheme = true
  showLastUpdated = false
