name = "Terminal Blog"
license = "MIT"
licenselink = "https://github.com/acruz/hugo-terminal-theme/blob/master/LICENSE"
description = "A minimal, terminal-style theme for technical blogs"
homepage = "https://abrahamsustaita.com/"
tags = ["blog", "minimal", "dark", "terminal", "technical"]
features = ["syntax highlighting", "responsive"]
min_version = "0.80.0"

[author]
  name = "Abraham Sustaita"
  homepage = "https://abrahamsustaita.com/"
